name: Push commit
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          touch truc.txt
          git config --global user.name 'pntbr'
          git config --global user.email 'stephane@scopyleft.fr'
          git add .
          git commit -m "Automated report"
          git push
